### ISSUE TITLE
nao consigo instalar o modulo

### ISSUE THREAD

**Issue by marcelowu** [rafaelboschini/Grand.Plugin.Shipping.Correios#1]
instalei o modulo no ubuntu, nao mostra nada no painel admin.

**Comment by marcelowu** [comment]
How to upgrade plugin to 4.80
https://grandnode.com/how-to-upgrade-plugin-to-4800

**Comment by rafaelboschini** [comment]
No arquivo Description.txt, procure por SupportedVersions: 4.80 e troca para a versao do seu GrandNode, ai ira aparecer na lista de plugins.

**Comment by marcelowu** [comment]
ja apareceu, obrigado, mas nao sei se nao sabia de configurar ta aparecendo erro nao mostra valor calcurado. versao 4.6

**Comment by marcelowu** [comment]
e na versao 4.80.0 nao esta compilando

**Comment by marcelowu** [comment]
seria bom com adicionar frete internacional para webservice REST 
https://github.com/claudiosanches/woocommerce-correios/pull/167/files

**Comment by marcelowu** [comment]
obrigado, esta funcionando na versao 4.70
